version: 1.0.{build}
environment:
  access_token:
    secure: MzO0P1ZCOlzG4DJ313Xv9zzCHfQlx1Ngvkwt9pqYODOCVWNAKT8KNj7HkPnbCSPs
branches:
  only:
  - master
build_script:
- cmd: git config --global credential.helper store
on_success:
  - ps: Add-Content "$env:USERPROFILE\.git-credentials" "https://$($env:access_token):x-oauth-basic@github.com`n"
  - git config --global user.email "darrell.tunnell@googlemail.com"
  - git config --global user.name "dazinator"
  - git subtree push --prefix=public https://github.com/dazinator/PersonalBlog.git gh-pages