---
contentdir: "content"
layoutdir: "layouts"
publishdir: "public"
indexes:
  category: "categories"
baseurl: "http://darrelltunnell.net"
title: "Darrell Tunnell's Blog"
canonifyurls: true
languageCode: "en-us"
permalinks:
    post: /blog/:year/:month/:day/:title/
metadataformat: "yaml"
disqusShortname: "darrelltunnellsblog"
theme: "hugo-theme-bootstrap4-blog"
# number of posts to show on home/category/tag pages (Default: 10)
paginate: 5
# sidebar:
    # Optional about block for sidebar (can be Markdown)
#    about: "A simple Hugo theme based on the [Bootstrap v4 blog example](http://v4-alpha.getbootstrap.com/examples/blog/)."

      
...
