---
contentdir: "content"
layoutdir: "layouts"
publishdir: "public"
indexes:
  category: "categories"
baseurl: "http://darrelltunnell.net"
title: "Darrell Tunnell's Blog'"
canonifyurls: true
theme: "Lanyon"
permalinks:
    post: /blog/:year/:month/:day/:title/
metadataformat: "yaml"
disqusShortname: "darrelltunnellsblog"
...
